[connection.snowspark]
account = 'ts33775.ap-southeast-1'
user = 'VIJAYTDESHMUKH'
password = 'Vijaytdeshmukh@4513'
warehouse = 'COMPUTE_WH'
database = 'NEXUS'
schema = 'ATTENDENCE'
client_session_keep_alive = true
