access_key = 'AKIA6EC77OF46KMFSR7V'
secret_key = '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'
region = 'Asia Pacific (Mumbai) ap-south-1'

account = 'ts33775.ap-southeast-1'
user = 'VIJAYTDESHMUKH'
password = 'Vijaytdeshmukh@4513'
warehouse = 'COMPUTE_WH'
database = 'NEXUS'
schema = 'ATTENDENCE'
client_session_keep_alive = true
